"""add rubric_scores to submissions

Revision ID: 0f973aba6ba7
Revises: 581163bf51a0
Create Date: 2026-05-20 10:14:01.778080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f973aba6ba7'
down_revision = '581163bf51a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_scores', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('rubric_scores')

    # ### end Alembic commands ###
