"""add enrollment_status and auto_accept

Revision ID: 20d8c812708e
Revises: 800cef0f077e
Create Date: 2026-04-29 17:09:21.869325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d8c812708e'
down_revision = '800cef0f077e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_accept', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('auto_accept')

    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.drop_column('enrollment_status')

    # ### end Alembic commands ###
