"""add name_extension to users

Revision ID: 22fe0b2562a1
Revises: b3e1f9a042c8
Create Date: 2026-05-20 07:59:22.435183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22fe0b2562a1'
down_revision = 'b3e1f9a042c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_files_submission_id'), if_exists=True)

    op.execute('DROP TABLE IF EXISTS submission_files')
    op.execute('ALTER TABLE submissions DROP COLUMN IF EXISTS original_filename')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_extension', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name_extension')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.create_table('submission_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('submission_files_submission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_files_pkey'))
    )
    with op.batch_alter_table('submission_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_files_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###
