"""add analysis columns to submissions

Revision ID: 581163bf51a0
Revises: 22fe0b2562a1
Create Date: 2026-05-20 09:42:47.731932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581163bf51a0'
down_revision = '22fe0b2562a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('analyzed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('analyzed_at')
        batch_op.drop_column('analysis')

    # ### end Alembic commands ###
