"""add performance indexes

Revision ID: 7f2c82cb9323
Revises: add_uploaded_files
Create Date: 2026-05-13 15:58:15.917230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f2c82cb9323'
down_revision = 'add_uploaded_files'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: DROP TABLE submission_files and DROP COLUMN original_filename intentionally
    # excluded — these are legacy artifacts that are safe to leave in place.
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_class_id', ['class_id'], unique=False)

    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.create_index('ix_class_members_class_student', ['class_id', 'student_id'], unique=False)
        batch_op.create_index('ix_class_members_student', ['student_id'], unique=False)

    with op.batch_alter_table('class_teachers', schema=None) as batch_op:
        batch_op.create_index('ix_class_teachers_class_teacher', ['class_id', 'teacher_id'], unique=False)

    with op.batch_alter_table('edited_contents', schema=None) as batch_op:
        batch_op.create_index('ix_edited_contents_activity_id', ['activity_id'], unique=False)

    with op.batch_alter_table('feed_events', schema=None) as batch_op:
        batch_op.create_index('ix_feed_events_class_id', ['class_id'], unique=False)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index('ix_group_members_group_id', ['group_id'], unique=False)
        batch_op.create_index('ix_group_members_student_id', ['student_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'is_read'], unique=False)

    with op.batch_alter_table('session_attendance', schema=None) as batch_op:
        batch_op.create_index('ix_session_attendance_session_id', ['session_id'], unique=False)

    with op.batch_alter_table('stream_posts', schema=None) as batch_op:
        batch_op.create_index('ix_stream_posts_class_id', ['class_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_activity_student', ['activity_id', 'student_id'], unique=False)
        batch_op.create_index('ix_submissions_student_id', ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_submissions_student_id')
        batch_op.drop_index('ix_submissions_activity_student')

    with op.batch_alter_table('stream_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_stream_posts_class_id')

    with op.batch_alter_table('session_attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_session_attendance_session_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index('ix_group_members_student_id')
        batch_op.drop_index('ix_group_members_group_id')

    with op.batch_alter_table('feed_events', schema=None) as batch_op:
        batch_op.drop_index('ix_feed_events_class_id')

    with op.batch_alter_table('edited_contents', schema=None) as batch_op:
        batch_op.drop_index('ix_edited_contents_activity_id')

    with op.batch_alter_table('class_teachers', schema=None) as batch_op:
        batch_op.drop_index('ix_class_teachers_class_teacher')

    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.drop_index('ix_class_members_student')
        batch_op.drop_index('ix_class_members_class_student')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_class_id')

    op.create_table('submission_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('submission_files_submission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_files_pkey'))
    )
    with op.batch_alter_table('submission_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_files_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###
