"""add ClassTeacher and invite_type

Revision ID: d4c0ff760e79
Revises: 20d8c812708e
Create Date: 2026-04-29 19:21:35.896531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c0ff760e79'
down_revision = '20d8c812708e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_invites', schema=None) as batch_op:
        batch_op.drop_column('invite_type')

    op.drop_table('class_teachers')
    # ### end Alembic commands ###
